language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: RzMuJOJVHozSXRtuuMXR2n+xcsdcsCWmLKGFXbjiBWiqOZAkVl5VV+z/UT08oNOo+1bYgEbM4p2eIezUehhPbqbcjnJYJ72jBeeWdc7wurd1kiCj/UaZJzktNBXZJ/+wL+Kgn8rvUb37lRgpeg9oURnpjaLuwbRNjg7l1639UMMzGaBwc2rt9cGVzbkjtgeMcShHHcl9ZuVY+RBPOSe+otHGdy+rZBlqkl/kbLprVMhWtUzw5VtAOMG2bYOgQnGSzCQh5BD1wprenzeeKYxIXKivq4+3rg1NC7Qw0bo4c+JMX6/XYx4g4VZdq0QPCwwMmcVLPULBF85eWkVpArC+lOKYDlDo2wxIkSXT+7MD2fssjHL3Qe73FWvA53v2BbOAlYXDWXlC1i+fyxEMcw85kHrSVU8mlEjwc5ATmivYURcXw/Vn2KpYySJYC2a04nBG/t8A9R3xdsECr9wjpxYYIuqQR+5IgWSJo/QcwPg11Iyqu1nmwtmihYFCR3d03bqlEIMAuEWC4WkFLoeWl100lHB/4Bq3qWUrr3NUr4rcl4mwM1ZoOV8qIYy/fxpDGz9Djl/nxeWbnvKHapOHaJ3QsHOfBKOw2x5PvYk5yRHr9KwCnLAELZ+booddS2FdwDmxLh2bNIwDJ54JZdHyCA0Tli8dixRfUaxcbW0fTdByO/4=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
